# d_zonalst&cluster_data_combine_visualize is designed to combine Cluster and building parameters for easier visualization of subsequent indicators.

This code is intended to extract X, Y, and Cluster data separately, and then combine it with canopy and building parameters to generate the final_cities_cluster_with_index.shp file.

Here is the specific process breakdown:

#### 10 Data Preprocessing
> 10_01 Extract X, Y, 'Place', 'City Name', 'Place ID','Sum ID' and 'Cluster' data separately to obtain an original CSV file.
> 10_02 csv file into shapefile
> 10_03 Convert the shapefile to WGS 1984.

#### 11 Indicator Visualization
> 11_01 This code aims to normalize the 'MEAN', 'FAR', and 'biodensity' indicators.
> 11_01 shapefile into csv
> 11_02 Plot the corresponding indicator images.

# 10_01 Extract X, Y, 'Place', 'City Name', 'Place ID','Sum ID' and 'Cluster' data separately to obtain an original CSV file.

In [11]:
import pandas as pd
import os
import numpy as np

cluster_origin_file=rf'D:\file\d_som\223_cities_combined_moving_ave_cluster_sort.csv'
output_file_path=rf'D:\file\d_som'
# 创建输出文件所在的目录
os.makedirs(output_file_path, exist_ok=True)

data = pd.read_csv(cluster_origin_file)
data_xy = data.iloc[:, 0:2]  # Assuming that the first two columns are not features
# 将结果保存为CSV文件，并加入前两列数据
df = pd.DataFrame(data_xy)
# 确保这些列存在
for col in ['Place', 'City Name', 'Place ID','Sum ID', 'K_5', 'K_12', 'K_20', 'K_26']:
    if col in data.columns:
        df[col] = data[col]

output_file =  os.path.join(output_file_path,rf'223_cities_combined_moving_ave_cluster_sort_xy.csv')
df.to_csv(output_file, index=False)

In [12]:
data

,X,Y,gf_Day2017_001_to_gf_Day2017_007,gf_Day2017_002_to_gf_Day2017_008,gf_Day2017_003_to_gf_Day2017_009,gf_Day2017_004_to_gf_Day2017_010,gf_Day2017_005_to_gf_Day2017_011,gf_Day2017_006_to_gf_Day2017_012,gf_Day2017_007_to_gf_Day2017_013,gf_Day2017_008_to_gf_Day2017_014,...,gf_Nit2019_359_to_gf_Nit2019_365,Place,City Name,Place ID,Sum ID,Hemisphere,K_5,K_12,K_20,K_26
0,3.679990e+05,5.108440e+06,0.421664,0.484929,0.635950,0.790895,1.190424,0.211774,0.702198,0.749765,...,-0.701099,0,Lyon [FRA],0,0,1,1,1,5,11
1,3.689514e+05,5.108440e+06,0.807378,0.913501,0.964521,0.962323,1.290424,0.697488,1.145055,1.092622,...,-1.029670,0,Lyon [FRA],1,1,1,1,1,9,11
2,3.699037e+05,5.108440e+06,0.921664,0.984929,1.035950,1.019466,1.304710,0.626060,1.045055,1.021193,...,-0.858242,0,Lyon [FRA],2,2,1,1,1,9,11
3,3.718085e+05,5.108440e+06,0.821664,0.913501,0.978807,0.976609,1.247567,0.297488,0.845055,0.749765,...,0.227473,0,Lyon [FRA],3,3,1,1,1,5,11
4,3.727608e+05,5.108440e+06,-0.092622,-0.029356,0.035950,0.019466,0.090424,-0.959655,-0.554945,-0.664521,...,-0.472527,0,Lyon [FRA],4,4,1,1,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142501,1.131674e+07,2.506661e+06,3.150000,2.971429,2.821429,2.628571,2.764286,2.721429,2.892857,2.850000,...,1.300000,244,"Yulin, Guangxi [CHN]",157,142507,1,2,6,8,18
142502,1.131770e+07,2.505688e+06,2.464286,2.257143,2.107143,1.842857,2.007143,1.907143,1.864286,1.707143,...,0.728571,244,"Yulin, Guangxi [CHN]",158,142508,1,1,1,5,11
142503,1.131962e+07,2.504715e+06,2.507143,2.428571,2.278571,2.028571,2.350000,2.264286,2.250000,2.107143,...,0.428571,244,"Yulin, Guangxi [CHN]",159,142509,1,2,4,4,8
142504,1.132058e+07,2.504715e+06,1.950000,1.814286,1.707143,1.471429,1.935714,1.878571,1.892857,1.778571,...,0.100000,244,"Yulin, Guangxi [CHN]",160,142510,1,2,4,4,8
142505,1.131962e+07,2.503742e+06,2.964286,2.928571,2.764286,2.428571,2.607143,2.464286,2.264286,2.007143,...,0.257143,244,"Yulin, Guangxi [CHN]",161,142511,1,2,4,4,8

In [13]:
df

,X,Y,Place,City Name,Place ID,Sum ID,K_5,K_12,K_20,K_26
0,3.679990e+05,5.108440e+06,0,Lyon [FRA],0,0,1,1,5,11
1,3.689514e+05,5.108440e+06,0,Lyon [FRA],1,1,1,1,9,11
2,3.699037e+05,5.108440e+06,0,Lyon [FRA],2,2,1,1,9,11
3,3.718085e+05,5.108440e+06,0,Lyon [FRA],3,3,1,1,5,11
4,3.727608e+05,5.108440e+06,0,Lyon [FRA],4,4,1,1,3,2
...,...,...,...,...,...,...,...,...,...,...
142501,1.131674e+07,2.506661e+06,244,"Yulin, Guangxi [CHN]",157,142507,2,6,8,18
142502,1.131770e+07,2.505688e+06,244,"Yulin, Guangxi [CHN]",158,142508,1,1,5,11
142503,1.131962e+07,2.504715e+06,244,"Yulin, Guangxi [CHN]",159,142509,2,4,4,8
142504,1.132058e+07,2.504715e+06,244,"Yulin, Guangxi [CHN]",160,142510,2,4,4,8
142505,1.131962e+07,2.503742e+06,244,"Yulin, Guangxi [CHN]",161,142511,2,4,4,8

# 10_02 csv file into shapefile

In [14]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# 定义 K 值

# 定义文件路径
csv_file = r"D:\file\d_som/223_cities_combined_moving_ave_cluster_sort_xy.csv"
shp_file = r"D:\file\d_som/223_cities_combined_moving_ave_cluster_sort_xy.shp"

# 读取 CSV 文件
df = pd.read_csv(csv_file)

# 创建 GeoDataFrame
geometry = [Point(xy) for xy in zip(df['X'], df['Y'])]
gdf = gpd.GeoDataFrame(df, geometry=geometry)

# 定义坐标系
# 使用 PROJ 字符串定义 Sinusoidal 投影
sinusoidal_proj = "+proj=sinu +R=6371007.181 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
gdf.set_crs(sinusoidal_proj, inplace=True)  # 设置输入坐标系为 Sinusoidal

# 将坐标系转换为 WGS 1984
gdf = gdf.to_crs(epsg=4326)  # WGS 1984 的 EPSG 代码是 4326

# 保存为 Shapefile
gdf.to_file(shp_file)

print("Shapefile 生成完成：", shp_file)

Shapefile 生成完成： D:\file\d_som/223_cities_combined_moving_ave_cluster_sort_xy.shp

In [16]:
input_shapefile = r"D:\file\e_index\223cities_output_file(+isf+elev_slope).shp"
# 读取输入 Shapefile
gdf = gpd.read_file(input_shapefile)
gdf
# cluster_origin_file=rf'D:\file\d_som\223_cities_combined_moving_ave_cluster_sort.csv'

,FID_1,LandArea,Buiheight,BldArea,CoverRatio,FAR,GreenArea,GrHeight,GreenRatio,GrVolRatio,...,MIN_DistMT,ImpSurf,ISF,elev_mean,elev_std,elev_range,slope_mean,slope_std,slope_rang,geometry
0,0,860557.573123,0.496248,38941.0,0.045251,0.007485,470933.730049,3.275140,0.547243,1.792296,...,0.000000,75069.904953,0.087234,151.107239,53.593437,195.805069,79.617691,28.708534,89.998863,"POLYGON ((4.75752 45.94167, 4.76950 45.94167, ..."
1,1,860557.573123,0.779559,83679.0,0.097238,0.025268,425270.763234,1.443066,0.494180,0.713135,...,0.000000,162441.433020,0.188763,158.960312,52.299206,228.929352,80.510780,27.579367,89.998955,"POLYGON ((4.76950 45.94167, 4.78149 45.94167, ..."
2,2,860557.573123,1.395443,180182.0,0.209378,0.097392,629928.879563,1.534113,0.732001,1.122972,...,0.000000,283117.355371,0.328993,169.091583,56.861111,251.901779,87.204224,15.574681,89.998810,"POLYGON ((4.78149 45.94167, 4.79347 45.94167, ..."
3,3,860557.573123,1.559270,171185.0,0.198923,0.103392,708601.219980,3.602671,0.823421,2.966515,...,0.000000,197066.001492,0.228998,181.237778,69.076370,275.822510,89.989899,0.013793,0.175903,"POLYGON ((4.80545 45.94167, 4.81744 45.94167, ..."
4,4,860557.573123,1.345770,125281.0,0.145581,0.065306,675041.690152,4.928443,0.784424,3.865987,...,0.000000,164841.749725,0.191552,206.999008,77.477348,282.482147,89.991577,0.010472,0.109024,"POLYGON ((4.81744 45.94167, 4.82942 45.94167, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151346,226,860557.572560,0.156929,46678.0,0.054242,0.002837,789876.215680,6.762658,0.917866,6.207211,...,20499.378906,42919.233889,0.049874,31.723320,29.601707,70.190926,89.984436,0.021044,0.239128,"POLYGON ((-80.37998 33.82500, -80.36995 33.825..."
151347,227,860557.572561,0.118487,23961.0,0.027844,0.001100,717234.744607,7.684825,0.833454,6.404944,...,19410.886719,13996.954812,0.016265,29.654377,27.764278,71.169693,89.985382,0.026387,0.523796,"POLYGON ((-80.40224 33.81667, -80.39221 33.816..."
151348,228,860557.572562,0.134153,35996.0,0.041829,0.001870,646988.047305,5.404497,0.751824,4.063232,...,20827.177734,10212.063970,0.011867,29.938974,27.875881,67.519257,89.965187,0.046566,0.630348,"POLYGON ((-80.39441 33.80833, -80.38438 33.808..."
151349,229,860557.572558,0.115465,22279.0,0.025889,0.000996,290965.013254,5.338340,0.338112,1.804958,...,21472.291016,13211.411430,0.015352,30.381454,28.274424,68.897896,89.968628,0.054239,0.762207,"POLYGON ((-80.39661 33.80000, -80.38658 33.800..."
151350,230,860557.572559,0.133488,21837.0,0.025375,0.001129,298548.463531,5.870615,0.346924,2.036660,...,22223.457031,12782.933221,0.014854,31.382614,29.827698,75.465446,89.956863,0.154486,4.414314,"POLYGON ((-80.38658 33.80000, -80.37655 33.800..."

# 10_03 Convert the shapefile to WGS 1984.

In [17]:
import geopandas as gpd

# 设置输入和输出文件路径
input_shapefile = r"D:\file\e_index\223cities_output_file(+isf+elev_slope).shp"
output_shapefile = r"D:\file\e_index\223_cities_cluster_with_index_original.shp"
projection_file = r"D:\file\d_som\223_cities_combined_moving_ave_cluster_sort_xy.shp"

# 读取输入 Shapefile
gdf = gpd.read_file(input_shapefile)

# 读取投影 Shapefile
proj_gdf = gpd.read_file(projection_file)

utm_crs = gdf.estimate_utm_crs()
gdf = gdf.to_crs(utm_crs)
proj_gdf = proj_gdf.to_crs(utm_crs)

# 用缓冲区进行新的匹配
gdf_buffered = gdf.copy()
gdf_buffered['geometry'] = gdf_buffered.geometry.buffer(5)  # 5米缓冲区


gdf = gdf_buffered.sjoin(proj_gdf[['geometry',  'K_5', 'K_12', 'K_20', 'K_26', 'Place', 'Place ID', 'Sum ID', 'City Name']], how='left', predicate='intersects')

# 5. 替换 "Sum ID" 为空的情况，并同步修改 'Cluster', 'Place', 'Place ID'
fill_columns = ['Sum ID',  'K_5', 'K_12', 'K_20', 'K_26', 'Place', 'Place ID']
for col in fill_columns:
    gdf[col] = gdf[col].fillna(-9999)

# 6. 转换回 WGS 84 坐标系
gdf = gdf.to_crs("EPSG:4326")

# 7. 保存到 Shapefile
gdf.to_file(output_shapefile)

print(f"已成功进行空间连接，未匹配数据设为 -9999，并保存到 {output_shapefile}")

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\1150261906.py:34: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  gdf.to_file(output_shapefile)

已成功进行空间连接，未匹配数据设为 -9999，并保存到 D:\file\e_index\223_cities_cluster_with_index_original.shp

In [2]:
import geopandas as gpd

# 读取 shapefile
shp_path = r"D:\file\e_index\223_cities_cluster_with_index_original.shp"
gdf = gpd.read_file(shp_path)

print("'Sum ID' 列统计情况：")
print(gdf['Sum ID'].describe())  # 统计描述
print("\n唯一值数量：", gdf['Sum ID'].nunique())  # 统计唯一值个数
print("\n前10个 Sum ID 频次：")
print(gdf['Sum ID'].value_counts().head(10))  # 查看最常见的 10 个值及其数量

'Sum ID' 列统计情况：
count    151352.000000
mean      75674.694731
std       43693.313136
min       -9999.000000
25%       37836.750000
50%       75674.500000
75%      113513.250000
max      151353.000000
Name: Sum ID, dtype: float64

唯一值数量： 151349

前10个 Sum ID 频次：
Sum ID
-9999.0     3
 91495.0    2
 61502.0    1
 0.0        1
 1.0        1
 2.0        1
 3.0        1
 61486.0    1
 61472.0    1
 61473.0    1
Name: count, dtype: int64

In [ ]:
'''
这里需要手动删除重复值 和 nodata值
将 223_cities_cluster_with_index_original.shp
->>> 打开arcgis 把Sum ID = 91495 的右边的那个栅格删了
#########? 还有三个没有匹配的数据？
223_cities_cluster_with_index.shp
'''

In [19]:
import geopandas as gpd

# 读取 shapefile
shp_path = r"D:\file\e_index\223_cities_cluster_with_index_original.shp"
gdf = gpd.read_file(shp_path)

print("'Sum ID' 列统计情况：")
print(gdf['Sum ID'].describe())  # 统计描述
print("\n唯一值数量：", gdf['Sum ID'].nunique())  # 统计唯一值个数
print("\n前10个 Sum ID 频次：")
print(gdf['Sum ID'].value_counts().head(10))  # 查看最常见的 10 个值及其数量

'Sum ID' 列统计情况：
count    151352.000000
mean      66506.739746
std       44236.163301
min       -9999.000000
25%       28994.750000
50%       66832.500000
75%      104670.250000
max      142511.000000
Name: Sum ID, dtype: float64

唯一值数量： 142507

前10个 Sum ID 频次：
Sum ID
-9999.0      8845
 91495.0        2
 138268.0       1
 138270.0       1
 138271.0       1
 138272.0       1
 138273.0       1
 138274.0       1
 138275.0       1
 0.0            1
Name: count, dtype: int64

In [20]:
import geopandas as gpd

# 读取 shapefile
shp_path = r"D:\file\e_index\223_cities_cluster_with_index.shp"
gdf = gpd.read_file(shp_path)

print("'Sum ID' 列统计情况：")
print(gdf['Sum ID'].describe())  # 统计描述
print("\n唯一值数量：", gdf['Sum ID'].nunique())  # 统计唯一值个数
print("\n前10个 Sum ID 频次：")
print(gdf['Sum ID'].value_counts().head(10))  # 查看最常见的 10 个值及其数量

'Sum ID' 列统计情况：
count    142506.000000
mean      71255.089147
std       41139.586660
min           0.000000
25%       35628.250000
50%       71254.500000
75%      106882.750000
max      142511.000000
Name: Sum ID, dtype: float64

唯一值数量： 142506

前10个 Sum ID 频次：
Sum ID
0.0         1
138272.0    1
138266.0    1
138267.0    1
138268.0    1
138269.0    1
138270.0    1
138271.0    1
138273.0    1
138281.0    1
Name: count, dtype: int64

# 清理了北半球的数据

In [4]:
import geopandas as gpd

# 读取 shapefile
shp_path = r"D:\file\e_index\223_cities_cluster_with_index_original.shp"
gdf = gpd.read_file(shp_path)

print("'Sum ID' 列统计情况：")
print(gdf['Sum ID'].describe())  # 统计描述
print("\n唯一值数量：", gdf['Sum ID'].nunique())  # 统计唯一值个数
print("\n前10个 Sum ID 频次：")
print(gdf['Sum ID'].value_counts().head(10))  # 查看最常见的 10 个值及其数量

'Sum ID' 列统计情况：
count    151352.000000
mean      66506.739746
std       44236.163301
min       -9999.000000
25%       28994.750000
50%       66832.500000
75%      104670.250000
max      142511.000000
Name: Sum ID, dtype: float64

唯一值数量： 142507

前10个 Sum ID 频次：
Sum ID
-9999.0      8845
 91495.0        2
 138268.0       1
 138270.0       1
 138271.0       1
 138272.0       1
 138273.0       1
 138274.0       1
 138275.0       1
 0.0            1
Name: count, dtype: int64

In [9]:
import geopandas as gpd

# 1. 读取两个图层
file = r'D:\file\a_clip_data\a_original\city_SHP\a_city\CFA_100km_City_edited\CFA_100km_City_edited_clean.shp'
city_name = gpd.read_file(file)  # 如果有韩文字段，注意编码

shp_path = r"D:\file\e_index\223_cities_cluster_with_index.shp"
gdf = gpd.read_file(shp_path)

# 2. 只保留 city_name 中需要的列（FID_1, NM_EN2, MSA_EN2）
keep_cols = ['FID_1','UC_NM_MN', 'NM_EN2', 'MSA_EN2']  # 如果不需要 MSA_EN2，就去掉
city_small = city_name[keep_cols]

# 3. 按 gdf['Place'] == city_small['FID_1'] 合并
gdf_merged = gdf.merge(
    city_small,
    left_on='Place',
    right_on='FID_1',
    how='left'   # how='left' 保证 gdf 中所有行都保留；city_small 中找不到则填 NaN
)

# 4. 查看结果
#    这时 gdf_merged 会多出两个列：FID_1 (重复了) 和 NM_EN2（以及 MSA_EN2）
print(gdf_merged.columns.tolist())
print(gdf_merged[['Place','UC_NM_MN', 'NM_EN2', 'MSA_EN2']].head())

# 5. （可选）如果不想保留多余的 FID_1 列，可以删除：
gdf_merged = gdf_merged.drop(columns=['FID_1_y'])

# 5. 将合并后的 GeoDataFrame 写出到新的 Shapefile
out_path = r"D:\file\e_index\223_cities_cluster_with_index_clean.shp"
gdf_merged.to_file(out_path, encoding='utf-8')

print(f"✔ 合并结果已保存到：{out_path}")

['FID_1_x', 'LandArea', 'Buiheight', 'BldArea', 'CoverRatio', 'FAR', 'GreenArea', 'GrHeight', 'GreenRatio', 'GrVolRatio', 'MIN_DistWB', 'MIN_DistGL', 'MIN_DistMT', 'ImpSurf', 'ISF', 'elev_mean', 'elev_std', 'elev_range', 'slope_mean', 'slope_std', 'slope_rang', 'index_righ', 'Cluster', 'Place', 'Place ID', 'Sum ID', 'City Name', 'geometry', 'FID_1_y', 'UC_NM_MN', 'NM_EN2', 'MSA_EN2']
   Place    UC_NM_MN NM_EN2             MSA_EN2
0    0.0  Lyon [FRA]   Lyon  Metropolis of Lyon
1    0.0  Lyon [FRA]   Lyon  Metropolis of Lyon
2    0.0  Lyon [FRA]   Lyon  Metropolis of Lyon
3    0.0  Lyon [FRA]   Lyon  Metropolis of Lyon
4    0.0  Lyon [FRA]   Lyon  Metropolis of Lyon
✔ 合并结果已保存到：D:\file\e_index\223_cities_cluster_with_index_clean.shp

# 11_01 shapefile into csv

In [21]:
import geopandas as gpd
import pandas as pd
# 读取 Shapefile 文件
shp_path = r"D:\file\e_index\223_cities_cluster_with_index.shp"
output_path = r"D:\file\e_index\223_cities_cluster_with_index.csv"

# # 使用 GeoPandas 读取 Shapefile
gdf = gpd.read_file(shp_path)

# 将 GeoDataFrame 转换为 DataFrame
df = pd.DataFrame(gdf)

# 保存为 CSV 文件
df.to_csv(output_path, index=False)

print(f"Shapefile 已成功转换为 CSV，结果已保存到 {output_path}")

Shapefile 已成功转换为 CSV，结果已保存到 D:\file\e_index\223_cities_cluster_with_index.csv

# 11_02 Plot the corresponding indicator images.

In [36]:
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import os
#
# def plot_cluster_histograms(input_csv_path, columns_to_plot, K):
#     # 读取数据
#     df = pd.read_csv(input_csv_path)
#
#     # 创建绘图
#     for cluster_id in range(K):
#         # 选择属于当前 cluster_id 的数据
#         cluster_data = df[df[f'Cluster'] == cluster_id]
#         # 过滤掉值为 -9999 的数据
#         cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
#
#
#         # **输出当前 cluster 变量的统计信息**
#         print(f"\n==== Cluster {cluster_id} (K={K}) data ====")
#         print(cluster_data[columns_to_plot].describe())
#
#         # 创建直方图图像
#         plt.figure(figsize=(10, 6))
#
#         # 绘制每个列的直方图
#         for column in columns_to_plot:
#             sns.histplot(cluster_data[column], bins=10, kde=False, label=f'{column} Histogram', stat="density")
#             #print(f"绘制直方图: {column} (Cluster {cluster_id}) - 数据点数: {cluster_data[column].count()}")
#
#         # 设置图像标题和标签
#         plt.title(f'Cluster {cluster_id} Histograms (K={K})')
#         plt.xlabel('Value')
#         plt.ylabel('Density')
#
#         # # 固定横纵坐标范围
#         # plt.xlim(-0.5,20)
#         # plt.ylim(0, 5)
#
#         plt.legend()
#
#         # 保存直方图图像
#         output_hist_path = os.path.join (output_folder, rf'K={K}_histogram_cluster_{cluster_id}.png')
#         plt.savefig(output_hist_path)
#         plt.close()
#         #print(f"直方图已保存: {output_hist_path}")
#
#         # 创建 KDE 图像
#         plt.figure(figsize=(10, 6))
#
#         # 绘制每个列的 KDE 图
#         for column in columns_to_plot:
#             sns.kdeplot(cluster_data[column], label=f'{column} KDE')
#             #print(f"绘制 KDE: {column} (Cluster {cluster_id}) - 数据点数: {cluster_data[column].count()}")
#
#         # 设置图像标题和标签
#         plt.title(f'Cluster {cluster_id} KDE Plots (K={K})')
#         plt.xlabel('Value')
#         plt.ylabel('Density')
#
#         # # 固定横纵坐标范围
#         # plt.xlim(-0.5,20)
#         # plt.ylim(0, 5)
#
#         plt.legend()
#
#         # 保存 KDE 图像
#         output_kde_path = os.path.join (output_folder, rf'K={K}_kdeplot_cluster_{cluster_id}.png')
#         plt.savefig(output_kde_path)
#         plt.close()
#         #print(f"KDE 图像已保存: {output_kde_path}")
#
# def plot_cluster_analysis(input_csv_path, columns_to_plot, K):
#     # 读取数据
#     df = pd.read_csv(input_csv_path)
#
#     # 创建绘图
#     for cluster_id in range(K):
#         # 选择属于当前 cluster_id 的数据
#         cluster_data = df[df[f'Cluster'] == cluster_id]
#         # 过滤掉值为 -9999 的数据
#         cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
#
#         # **输出统计信息**
#         #print(f"\n==== Cluster {cluster_id} (K={K}) data ====")
#         #print(cluster_data[columns_to_plot].describe())
#
#         # 将数据从宽格式转换为长格式
#         cluster_data_melted = cluster_data.melt(id_vars=[f'Cluster'], value_vars=columns_to_plot, var_name='Variable', value_name='Value')
#
#         # 创建一个新的图像
#         plt.figure(figsize=(12, 8))
#
#         # 绘制小提琴图
#         sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
#
#         # 绘制箱线图
#         sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
#
#         # **输出每个变量的统计信息**
#         # for column in columns_to_plot:
#         #     print(f"绘制箱线图 & 小提琴图: {column} (Cluster {cluster_id}) - 数据点数: {cluster_data[column].count()}")
#
#         # 设置图像标题和标签
#         plt.title(f'Cluster {cluster_id} Data Distribution')
#         plt.xlabel('Variable')
#         plt.ylabel('Value')
#         # plt.ylim(-1.5, 14)
#         # 调整布局
#         plt.tight_layout()
#
#         # 保存图像
#         output_image_path = os.path.join (output_folder, rf'K={K}_boxplot_cluster_{cluster_id}.png')
#
#         plt.savefig(output_image_path)
#         plt.close()
#         #print(f"箱线图 & 小提琴图已保存: {output_image_path}")

# 11_02 ['Buiheight', 'CoverRatio', 'FAR', 'GreenRatio', 'GrVolRatio,'ISF']

In [ ]:
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import os
#
# import os
# import numpy as np
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
#
# def plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder):
#     # 读取数据
#     df = pd.read_csv(input_csv_path)
#
#     # 创建一个空的 DataFrame 用于存储所有 cluster 的统计数据
#     all_cluster_stats = []
#
#     # 遍历每个 cluster 进行绘制
#     for cluster_id in range(K):
#         # 选择属于当前 cluster_id 的数据
#         cluster_data = df[df[f'Cluster'] == cluster_id]
#         # 过滤掉值为 -9999 的数据
#         cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
#         # 输出 describe() 的 count 为整数
#         describe_output = cluster_data[columns_to_plot].describe().transpose()
#         describe_output['count'] = describe_output['count'].astype(int)
#
#         # 记录 cluster 统计信息
#         describe_output['Cluster'] = cluster_id
#         all_cluster_stats.append(describe_output)
#
#         # 打印统计信息
#         print(f"\n==== Cluster {cluster_id} (K={K}) data ====")
#         print(describe_output)
#
#         # 创建图像
#         plt.figure(figsize=(10, 6))
#
#         for column in columns_to_plot:
#             # 绘制直方图
#             sns.histplot(cluster_data[column], bins=10, kde=False, label=f'{column} Histogram', stat="proportion", alpha=0.3)
#
#             # 计算直方图数据
#             counts, bin_edges = np.histogram(cluster_data[column], bins=10, density=False)
#             total_count = counts.sum()  # 总样本数
#             proportions = counts / total_count  # 计算 proportion
#
#             # 计算 bin 的中心位置
#             bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
#
#             # 绘制 proportion 曲线
#             plt.plot(bin_centers, proportions, marker='o', linestyle='-', label=f'{column} Proportion Curve')
#
#         plt.title(f'Cluster {cluster_id} Histogram with Proportion Curve')
#         plt.xlabel('Value')
#         plt.ylabel('Proportion')
#         plt.xlim(-0.5, 10)
#         plt.ylim(0, 1)
#         plt.legend()
#
#         # 保存直方图图像
#         output_hist_path = os.path.join(output_folder, rf'K={K}_histogram_cluster_{cluster_id}.png')
#         plt.savefig(output_hist_path)
#         plt.close()  # 关闭图像，避免影响下一个 cluster
#
#
#     # 合并所有统计数据到一个 DataFrame
#     stats_df = pd.concat(all_cluster_stats)
#     stats_df.to_csv(os.path.join(output_folder, 'cluster_stats.csv'))
#
# def plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder):
#     # 读取数据
#     df = pd.read_csv(input_csv_path)
#
#     # 创建绘图
#     for cluster_id in range(K):
#         # 选择属于当前 cluster_id 的数据
#         cluster_data = df[df[f'Cluster'] == cluster_id]
#         # 过滤掉值为 -9999 的数据
#         cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
#
#         # 将数据从宽格式转换为长格式
#         cluster_data_melted = cluster_data.melt(id_vars=[f'Cluster'], value_vars=columns_to_plot, var_name='Variable', value_name='Value')
#
#         # 创建一个新的图像
#         plt.figure(figsize=(12, 8))
#
#         # 绘制小提琴图
#         sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
#
#         # 绘制箱线图
#         sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
#
#         # 设置图像标题和标签
#         plt.title(f'Cluster {cluster_id} Data Distribution')
#         plt.xlabel('Variable')
#         plt.ylabel('Value')
#         plt.ylim(-1, 15)
#         plt.tight_layout()
#
#         # 保存图像
#         output_image_path = os.path.join(output_folder, rf'K={K}_boxplot_cluster_{cluster_id}.png')
#
#         plt.savefig(output_image_path)
#         plt.close()
#
# # 运行代码
# input_csv_path = r"D:\file\e_index/223_cities_cluster_with_index.csv"
# columns_to_plot = ['Buiheight', 'CoverRatio', 'FAR', 'GreenRatio', 'GrVolRatio','ISF']
#
# for K in range(11, 12):
#     output_folder = rf'D:\file\e_index\fig\bui'
#     os.makedirs(output_folder, exist_ok=True)
#
#     plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder)
#     plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder)

In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 创建一个空的 DataFrame 用于存储所有 cluster 的统计数据
    all_cluster_stats = []

    # 遍历每个 cluster 进行绘制
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'K_{K}'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
        # 输出 describe() 的 count 为整数
        describe_output = cluster_data[columns_to_plot].describe().transpose()
        describe_output['count'] = describe_output['count'].astype(int)

        # 记录 cluster 统计信息
        describe_output[f'K_{K}'] = cluster_id
        all_cluster_stats.append(describe_output)

        # 打印统计信息
        print(f"\n==== K_{K} {cluster_id} (K={K}) data ====")
        print(describe_output)

        # 创建图像
        plt.figure(figsize=(10, 6))

        for column in columns_to_plot:
            # 绘制直方图
            sns.histplot(cluster_data[column], bins=20, kde=False, label=f'{column} Histogram', stat="proportion", alpha=0.3)

            # 计算直方图数据
            counts, bin_edges = np.histogram(cluster_data[column], bins=10, density=False)
            total_count = counts.sum()  # 总样本数
            proportions = counts / total_count  # 计算 proportion

            # 计算 bin 的中心位置
            bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

            # 绘制 proportion 曲线
            plt.plot(bin_centers, proportions, marker='o', linestyle='-', label=f'{column} Proportion Curve')

        plt.title(f'K_{K} {cluster_id} Histogram with Proportion Curve')
        plt.xlabel('Value')
        plt.ylabel('Proportion')
        plt.xlim(0, 2.5)
        plt.ylim(0, 1)
        plt.legend()

        # 保存直方图图像
        output_hist_path = os.path.join(output_folder, rf'K={K}_histogram_cluster_{cluster_id}.png')
        plt.savefig(output_hist_path)
        plt.close()  # 关闭图像，避免影响下一个 cluster


    # 合并所有统计数据到一个 DataFrame
    stats_df = pd.concat(all_cluster_stats)
    stats_df.to_csv(os.path.join(output_folder, 'cluster_stats.csv'))

def plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 创建绘图
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'K_{K}'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]

        # 将数据从宽格式转换为长格式
        cluster_data_melted = cluster_data.melt(id_vars=[f'K_{K}'], value_vars=columns_to_plot, var_name='Variable', value_name='Value')

        # 创建一个新的图像
        plt.figure(figsize=(8, 6))

        # 绘制小提琴图
        sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')

        # 绘制箱线图
        sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

        # 设置图像标题和标签
        plt.title(f'K_{K} {cluster_id} Data Distribution')
        plt.xlabel('Variable')
        plt.ylabel('Value')
        plt.ylim(-0.1, 1.5)
        plt.tight_layout()

        # 保存图像
        output_image_path = os.path.join(output_folder, rf'K={K}_boxplot_cluster_{cluster_id}.png')

        plt.savefig(output_image_path)
        plt.close()

# 运行代码
input_csv_path = r"D:\file\e_index\223_cities_cluster_with_index.csv"
columns_to_plot = ['CoverRatio', 'FAR', 'GreenRatio','ISF']

for K in [5,12,20,26]:
    output_folder = rf'D:\file\e_index\fig\bui_new\{K}'
    os.makedirs(output_folder, exist_ok=True)

    plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder)
    plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder)

==== K_5 0 (K=5) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  26167  0.135648  0.096093  3.486112e-06  0.062299  0.114283
FAR         26167  0.096928  0.164027  8.424770e-10  0.006270  0.029411
GreenRatio  26167  0.465455  0.237165  5.382494e-04  0.281252  0.427897
ISF         26167  0.308337  0.225940  8.112673e-05  0.127750  0.262247

                 75%       max  K_5
CoverRatio  0.187925  0.690947    0
FAR         0.107795  3.132435    0
GreenRatio  0.641469  1.019096    0
ISF         0.449243  0.990083    0

==== K_5 1 (K=5) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  27326  0.130207  0.084538  1.162037e-06  0.064220  0.118799
FAR         27326  0.077746  0.135317  2.227240e-10  0.007598  0.033597
GreenRatio  27326  0.686751  0.233273  8.081705e-04  0.540222  0.750996
ISF         27326  0.226689  0.188156  7.972207e-05  0.076658  0.176566

                 75%       max  K_5
CoverRatio  0.185005  0.671215    1
FAR         0.095135  3.566849    1
GreenRatio  0.874979  1.026082    1
ISF         0.331736  0.977504    1

==== K_5 2 (K=5) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  36949  0.136255  0.082383  1.162037e-06  0.074864  0.125517
FAR         36949  0.088702  0.158226  3.606189e-09  0.010197  0.037441
GreenRatio  36949  0.658537  0.223243  1.751060e-03  0.517297  0.714470
ISF         36949  0.248753  0.198694  8.199914e-05  0.097000  0.192742

                 75%       max  K_5
CoverRatio  0.183216  0.590271    2
FAR         0.096809  2.465962    2
GreenRatio  0.837679  1.014398    2
ISF         0.349352  0.992112    2

==== K_5 3 (K=5) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  27739  0.210483  0.101404  1.394445e-05  0.133465  0.202504
FAR         27739  0.222720  0.247292  6.856020e-10  0.045723  0.130451
GreenRatio  27739  0.517366  0.216270  5.594791e-04  0.353914  0.515840
ISF         27739  0.462963  0.241246  5.310926e-04  0.260691  0.453221

                 75%       max  K_5
CoverRatio  0.284817  0.580585    3
FAR         0.313662  2.162388    3
GreenRatio  0.689068  0.998684    3
ISF         0.651702  0.997670    3

==== K_5 4 (K=5) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio  23916  0.229560  0.087078  0.000446  0.169903  0.223648  0.283166
FAR         23916  0.238400  0.253113  0.000002  0.081788  0.152279  0.284075
GreenRatio  23916  0.612338  0.209195  0.000343  0.473042  0.647189  0.778098
ISF         23916  0.463669  0.227878  0.005985  0.277864  0.436551  0.634585

                 max  K_5
CoverRatio  0.703138    4
FAR         2.483490    4
GreenRatio  1.004794    4
ISF         0.996819    4

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

==== K_12 0 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  12412  0.115255  0.089472  3.486112e-06  0.048964  0.091985
FAR         12412  0.072032  0.138330  8.424770e-10  0.003742  0.016518
GreenRatio  12412  0.523012  0.266852  2.667314e-03  0.292078  0.509157
ISF         12412  0.246557  0.213353  8.112673e-05  0.078982  0.185097

                 75%       max  K_12
CoverRatio  0.158170  0.490610     0
FAR         0.068826  1.496670     0
GreenRatio  0.768428  1.019096     0
ISF         0.354729  0.988754     0

==== K_12 1 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  14733  0.101930  0.074241  1.162037e-06  0.045668  0.089433
FAR         14733  0.053031  0.120853  2.227240e-10  0.003650  0.016160
GreenRatio  14733  0.680050  0.244614  1.665732e-03  0.513188  0.750029
ISF         14733  0.175428  0.166948  7.972207e-05  0.051953  0.125219

                 75%       max  K_12
CoverRatio  0.143070  0.649123     1
FAR         0.051950  2.591573     1
GreenRatio  0.881983  1.026082     1
ISF         0.242468  0.963708     1

==== K_12 2 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   8356  0.198799  0.106629  1.394445e-05  0.115851  0.188030
FAR          8356  0.200253  0.239982  6.856020e-10  0.031546  0.112012
GreenRatio   8356  0.389260  0.175663  2.150296e-03  0.263936  0.372659
ISF          8356  0.468802  0.233624  5.020243e-04  0.287070  0.455186

                 75%       max  K_12
CoverRatio  0.273121  0.690947     2
FAR         0.277649  3.132435     2
GreenRatio  0.500831  0.998684     2
ISF         0.639045  0.997670     2

==== K_12 3 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   8210  0.129302  0.078246  4.299538e-05  0.070935  0.117347
FAR          8210  0.073734  0.120462  5.399503e-08  0.008649  0.030592
GreenRatio   8210  0.450567  0.204029  5.382494e-04  0.297073  0.425394
ISF          8210  0.303805  0.184581  2.602956e-04  0.160467  0.273159

                 75%       max  K_12
CoverRatio  0.174157  0.580585     3
FAR         0.086212  1.682644     3
GreenRatio  0.589842  0.997811     3
ISF         0.420669  0.958027     3

==== K_12 4 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  18436  0.106388  0.074121  1.162037e-06  0.051316  0.092593
FAR         18436  0.054399  0.120091  1.838343e-08  0.004239  0.016369
GreenRatio  18436  0.631770  0.233377  1.751060e-03  0.466288  0.686216
ISF         18436  0.203279  0.184115  8.199914e-05  0.066030  0.144976

                 75%       max  K_12
CoverRatio  0.143454  0.553607     4
FAR         0.050607  1.916308     4
GreenRatio  0.823724  1.014398     4
ISF         0.284086  0.990799     4

==== K_12 5 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  13277  0.183217  0.091604  6.507409e-05  0.117510  0.173051
FAR         13277  0.163917  0.210702  4.989014e-09  0.032777  0.085259
GreenRatio  13277  0.545094  0.226068  1.477017e-03  0.376533  0.557073
ISF         13277  0.393309  0.225804  1.468151e-03  0.203019  0.363304

                 75%       max  K_12
CoverRatio  0.242142  0.534459     5
FAR         0.203849  1.712297     5
GreenRatio  0.731214  0.991646     5
ISF         0.564032  0.994141     5

==== K_12 6 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  17981  0.160664  0.080117  4.299538e-05  0.105433  0.151633
FAR         17981  0.117480  0.181633  3.606189e-09  0.025152  0.061703
GreenRatio  17981  0.683033  0.211545  2.419976e-03  0.560324  0.737718
ISF         17981  0.283239  0.201223  2.487699e-04  0.130134  0.230463

                 75%       max  K_12
CoverRatio  0.205078  0.590271     6
FAR         0.127536  2.465962     6
GreenRatio  0.847443  1.010109     6
ISF         0.385303  0.992112     6

==== K_12 7 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   8045  0.271966  0.107460  0.000580  0.192768  0.284902  0.361398
FAR          8045  0.375364  0.296329  0.000005  0.121286  0.320003  0.574491
GreenRatio   8045  0.404984  0.162130  0.001119  0.289782  0.402542  0.516613
ISF          8045  0.634174  0.227430  0.009150  0.470545  0.669223  0.820308

                 max  K_12
CoverRatio  0.524949     7
FAR         1.727876     7
GreenRatio  0.972460     7
ISF         0.994384     7

==== K_12 8 (K=12) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  13654  0.166352  0.084001  9.296298e-06  0.103674  0.162829
FAR         13654  0.110611  0.147334  5.957378e-09  0.025140  0.070909
GreenRatio  13654  0.694232  0.217360  8.081705e-04  0.567070  0.749728
ISF         13654  0.294105  0.196494  3.454724e-04  0.132397  0.263189

                 75%       max  K_12
CoverRatio  0.226303  0.671215     8
FAR         0.144519  3.566849     8
GreenRatio  0.864782  1.017590     8
ISF         0.421808  0.977504     8

==== K_12 9 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   8342  0.206993  0.087010  0.000446  0.148191  0.198708  0.258842
FAR          8342  0.204178  0.258448  0.000003  0.056233  0.111029  0.220884
GreenRatio   8342  0.610269  0.212606  0.000343  0.471842  0.649607  0.780309
ISF          8342  0.405808  0.223773  0.005985  0.225801  0.356779  0.568163

                 max  K_12
CoverRatio  0.703138     9
FAR         2.483490     9
GreenRatio  1.004794     9
ISF         0.996819     9

==== K_12 10 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   8943  0.242613  0.086002  0.000478  0.185727  0.244101  0.302812
FAR          8943  0.262934  0.237296  0.000002  0.107972  0.193064  0.339848
GreenRatio   8943  0.582266  0.193364  0.000559  0.460864  0.612070  0.725626
ISF          8943  0.523373  0.209134  0.016489  0.365087  0.516876  0.679720

                 max  K_12
CoverRatio  0.584004    10
FAR         2.162388    10
GreenRatio  0.988329    10
ISF         0.994756    10

==== K_12 11 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   9708  0.224262  0.073807  0.001886  0.174534  0.222089  0.270076
FAR          9708  0.204722  0.205883  0.000021  0.089905  0.149560  0.234562
GreenRatio   9708  0.680873  0.182638  0.000384  0.576175  0.716674  0.819718
ISF          9708  0.420564  0.196014  0.006775  0.268330  0.399985  0.553229

                 max  K_12
CoverRatio  0.621567    11
FAR         2.302672    11
GreenRatio  0.997231    11
ISF         0.994344    11

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

==== K_20 0 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5692  0.183237  0.105774  7.901854e-05  0.098992  0.164720
FAR          5692  0.162722  0.204227  9.206175e-08  0.020897  0.074866
GreenRatio   5692  0.340553  0.174587  2.288127e-03  0.212488  0.321938
ISF          5692  0.426073  0.234206  7.340757e-04  0.237909  0.389015

                 75%       max  K_20
CoverRatio  0.259206  0.481678     0
FAR         0.230771  1.300173     0
GreenRatio  0.450770  1.002526     0
ISF         0.594235  0.988754     0

==== K_20 1 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   7324  0.115916  0.078648  1.057454e-04  0.058119  0.101964
FAR          7324  0.068431  0.138422  2.358936e-08  0.005333  0.021893
GreenRatio   7324  0.646633  0.233112  4.079327e-03  0.491599  0.704380
ISF          7324  0.221848  0.196516  8.112673e-05  0.073695  0.159699

                 75%       max  K_20
CoverRatio  0.155512  0.530655     1
FAR         0.067476  1.830768     1
GreenRatio  0.835648  1.013429     1
ISF         0.312085  0.990799     1

==== K_20 2 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5909  0.102145  0.069695  3.486112e-06  0.052519  0.087851
FAR          5909  0.046468  0.092929  8.424770e-10  0.004278  0.013916
GreenRatio   5909  0.415530  0.200626  6.316851e-03  0.267935  0.385407
ISF          5909  0.251860  0.162621  2.724024e-04  0.132966  0.217600

                 75%       max  K_20
CoverRatio  0.138217  0.490610     2
FAR         0.047243  1.336521     2
GreenRatio  0.540326  1.017439     2
ISF         0.340448  0.958027     2

==== K_20 3 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   6716  0.093901  0.074440  1.162037e-06  0.036437  0.078490
FAR          6716  0.049065  0.111819  2.227240e-10  0.002522  0.012705
GreenRatio   6716  0.644744  0.261308  3.440986e-03  0.447153  0.707423
ISF          6716  0.177410  0.171549  7.972207e-05  0.046696  0.126356

                 75%       max  K_20
CoverRatio  0.134510  0.473605     3
FAR         0.045830  1.647559     3
GreenRatio  0.869277  1.023550     3
ISF         0.252003  0.952591     3

==== K_20 4 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   9627  0.085511  0.066522  8.134261e-06  0.036892  0.069478
FAR          9627  0.034991  0.085796  1.838343e-08  0.002156  0.007786
GreenRatio   9627  0.630795  0.241899  6.543199e-03  0.446506  0.692829
ISF          9627  0.162469  0.165490  9.080081e-05  0.040595  0.104101

                 75%       max  K_20
CoverRatio  0.117140  0.553607     4
FAR         0.030023  1.916308     4
GreenRatio  0.831009  1.019096     4
ISF         0.229191  0.939037     4

==== K_20 5 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   6202  0.107315  0.073659  4.648149e-06  0.051597  0.096484
FAR          6202  0.054800  0.121841  1.475787e-09  0.004516  0.018582
GreenRatio   6202  0.711248  0.225008  1.665732e-03  0.579910  0.783699
ISF          6202  0.168616  0.161099  8.162428e-05  0.053835  0.118731

                 75%       max  K_20
CoverRatio  0.148340  0.545458     5
FAR         0.057059  1.884429     5
GreenRatio  0.887371  1.026082     5
ISF         0.225956  0.963708     5

==== K_20 6 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5832  0.203473  0.106582  1.394445e-05  0.122378  0.196036
FAR          5832  0.210452  0.246386  6.856020e-10  0.037393  0.124956
GreenRatio   5832  0.400923  0.181424  2.150296e-03  0.273053  0.383013
ISF          5832  0.479035  0.233689  5.020243e-04  0.299423  0.474994

                 75%       max  K_20
CoverRatio  0.276482  0.690947     6
FAR         0.292204  3.132435     6
GreenRatio  0.517785  0.998684     6
ISF         0.647096  0.997670     6

==== K_20 7 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   7234  0.142761  0.082967  4.299538e-05  0.082129  0.131272
FAR          7234  0.092882  0.143665  5.399503e-08  0.012931  0.041330
GreenRatio   7234  0.496356  0.218526  5.382494e-04  0.326819  0.480529
ISF          7234  0.319855  0.200765  2.602956e-04  0.155803  0.287743

                 75%       max  K_20
CoverRatio  0.190277  0.580585     7
FAR         0.108575  1.712297     7
GreenRatio  0.665483  0.997811     7
ISF         0.457575  0.981444     7

==== K_20 8 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio  10659  0.117544  0.070247  1.162037e-06  0.066115  0.108097
FAR         10659  0.056921  0.111029  3.606189e-09  0.007361  0.024226
GreenRatio  10659  0.664128  0.220095  1.751060e-03  0.525874  0.718613
ISF         10659  0.211008  0.171203  8.199914e-05  0.084518  0.163924

                 75%       max  K_20
CoverRatio  0.157148  0.509344     8
FAR         0.061343  1.650402     8
GreenRatio  0.839286  1.001758     8
ISF         0.288576  0.962970     8

==== K_20 9 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   7270  0.135127  0.076289  2.905093e-05  0.079824  0.126204
FAR          7270  0.078526  0.148484  7.572610e-08  0.012242  0.038319
GreenRatio   7270  0.715524  0.219650  2.042346e-03  0.583860  0.776117
ISF          7270  0.232595  0.178704  6.997669e-04  0.090665  0.191823

                 75%       max  K_20
CoverRatio  0.181363  0.671215     9
FAR         0.087737  3.566849     9
GreenRatio  0.890935  1.021964     9
ISF         0.327943  0.977504     9

==== K_20 10 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   7887  0.165534  0.085435  0.000163  0.105089  0.154409  0.215355
FAR          7887  0.135451  0.202097  0.000001  0.025183  0.066846  0.150068
GreenRatio   7887  0.668622  0.219604  0.002772  0.538820  0.720349  0.841575
ISF          7887  0.301619  0.216593  0.003911  0.132452  0.243883  0.421269

                 max  K_20
CoverRatio  0.514522    10
FAR         2.465962    10
GreenRatio  1.010109    10
ISF         0.982757    10

==== K_20 11 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   6989  0.210883  0.100665  8.250465e-05  0.135435  0.206666
FAR          6989  0.222598  0.237928  2.529111e-07  0.046565  0.139198
GreenRatio   6989  0.435794  0.194991  1.757826e-03  0.289930  0.425897
ISF          6989  0.488958  0.225562  1.468151e-03  0.308416  0.497313

                 75%       max  K_20
CoverRatio  0.284496  0.518891    11
FAR         0.320003  1.603622    11
GreenRatio  0.562692  0.980136    11
ISF         0.661894  0.992437    11

==== K_20 12 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   7563  0.186160  0.090562  6.507409e-05  0.122369  0.175798
FAR          7563  0.170009  0.217039  4.989014e-09  0.036370  0.089554
GreenRatio   7563  0.591174  0.221085  1.477017e-03  0.443106  0.622861
ISF          7563  0.385594  0.226762  1.835714e-03  0.198654  0.346598

                 75%       max  K_20
CoverRatio  0.242554  0.534459    12
FAR         0.203752  1.763074    12
GreenRatio  0.768947  0.991646    12
ISF         0.548625  0.994141    12

==== K_20 13 (K=20) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5514  0.169560  0.090562  9.296298e-06  0.101259  0.163420
FAR          5514  0.125012  0.160460  5.957378e-09  0.025470  0.074602
GreenRatio   5514  0.653790  0.224709  8.081705e-04  0.517382  0.705026
ISF          5514  0.292890  0.203042  3.454724e-04  0.132250  0.251023

                 75%       max  K_20
CoverRatio  0.233023  0.578438    13
FAR         0.162737  1.742979    13
GreenRatio  0.831836  1.015496    13
ISF         0.415975  0.975727    13

==== K_20 14 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   5595  0.289385  0.103735  0.003465  0.214916  0.303666  0.376554
FAR          5595  0.419208  0.305810  0.000076  0.154382  0.375384  0.625994
GreenRatio   5595  0.402111  0.161905  0.005757  0.287429  0.398825  0.513155
ISF          5595  0.674265  0.217823  0.019328  0.523478  0.716320  0.854921

                 max  K_20
CoverRatio  0.513738    14
FAR         1.727876    14
GreenRatio  0.912234    14
ISF         0.994384    14

==== K_20 15 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   9639  0.178785  0.075838  0.000387  0.126406  0.174013  0.228380
FAR          9639  0.124234  0.161004  0.000002  0.040461  0.084763  0.149327
GreenRatio   9639  0.704915  0.199772  0.002420  0.592231  0.757761  0.857888
ISF          9639  0.316968  0.194642  0.001752  0.161833  0.279765  0.439512

                 max  K_20
CoverRatio  0.590271    15
FAR         2.231233    15
GreenRatio  1.007191    15
ISF         0.992112    15

==== K_20 16 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   6998  0.204549  0.085387  0.000446  0.147868  0.196778  0.254157
FAR          6998  0.199711  0.258393  0.000003  0.055160  0.107876  0.208825
GreenRatio   6998  0.629261  0.201924  0.000343  0.503878  0.666875  0.787506
ISF          6998  0.392842  0.219328  0.005985  0.217664  0.341047  0.547619

                 max  K_20
CoverRatio  0.703138    16
FAR         2.483490    16
GreenRatio  1.004794    16
ISF         0.996819    16

==== K_20 17 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   7018  0.239048  0.089976  0.001470  0.175711  0.239648  0.305972
FAR          7018  0.265757  0.244746  0.000024  0.097535  0.189872  0.354020
GreenRatio   7018  0.579624  0.191535  0.000559  0.459197  0.609761  0.720948
ISF          7018  0.513368  0.215365  0.016489  0.347619  0.504172  0.677607

                 max  K_20
CoverRatio  0.527604    17
FAR         2.162388    17
GreenRatio  0.988329    17
ISF         0.994234    17

==== K_20 18 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   5707  0.219260  0.075112  0.002546  0.166249  0.217832  0.268194
FAR          5707  0.193437  0.192323  0.000044  0.083797  0.145208  0.222531
GreenRatio   5707  0.688758  0.188550  0.000384  0.582544  0.728943  0.832250
ISF          5707  0.408714  0.202987  0.006775  0.245607  0.388366  0.551412

                 max  K_20
CoverRatio  0.621567    18
FAR         2.027358    18
GreenRatio  0.997231    18
ISF         0.977522    18

==== K_20 19 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   6722  0.234458  0.075068  0.000478  0.187150  0.231043  0.278655
FAR          6722  0.226727  0.221852  0.000002  0.100252  0.162389  0.265644
GreenRatio   6722  0.636533  0.190376  0.000636  0.522354  0.668896  0.779572
ISF          6722  0.469843  0.198453  0.055831  0.313590  0.446850  0.609124

                 max  K_20
CoverRatio  0.611264    19
FAR         2.302672    19
GreenRatio  0.996508    19
ISF         0.994756    19

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.


==== K_26 0 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   3364  0.132190  0.087417  1.220139e-04  0.062884  0.119162
FAR          3364  0.084055  0.130462  2.358936e-08  0.005966  0.034301
GreenRatio   3364  0.624798  0.279543  2.667314e-03  0.399972  0.719998
ISF          3364  0.247057  0.213705  8.112673e-05  0.071351  0.180466

                 75%       max  K_26
CoverRatio  0.181498  0.477174     0
FAR         0.100045  1.063454     0
GreenRatio  0.853449  1.013429     0
ISF         0.375147  0.950064     0

==== K_26 1 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5682  0.163189  0.106309  1.278241e-05  0.080425  0.136306
FAR          5682  0.136173  0.197325  1.391685e-08  0.011209  0.044995
GreenRatio   5682  0.357682  0.169849  2.288127e-03  0.232067  0.339918
ISF          5682  0.383837  0.237513  7.340757e-04  0.194271  0.326260

                 75%       max  K_26
CoverRatio  0.231933  0.481678     1
FAR         0.179419  1.300173     1
GreenRatio  0.464066  0.997732     1
ISF         0.541186  0.988754     1

==== K_26 2 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   4278  0.087665  0.073387  1.162037e-06  0.031205  0.070559
FAR          4278  0.045860  0.113270  2.227240e-10  0.001820  0.009788
GreenRatio   4278  0.639308  0.256369  4.077971e-03  0.441558  0.695640
ISF          4278  0.181720  0.178806  7.972207e-05  0.043875  0.124703

                 75%       max  K_26
CoverRatio  0.124450  0.510497     2
FAR         0.038126  1.647559     2
GreenRatio  0.858714  1.026082     2
ISF         0.264627  0.952591     2

==== K_26 3 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5999  0.084261  0.068490  3.486112e-06  0.034650  0.068119
FAR          5999  0.037387  0.093650  8.424770e-10  0.002015  0.007668
GreenRatio   5999  0.556161  0.257476  6.316851e-03  0.336814  0.567863
ISF          5999  0.183673  0.169723  9.080081e-05  0.051224  0.136157

                 75%       max  K_26
CoverRatio  0.114304  0.490610     3
FAR         0.029571  1.496670     3
GreenRatio  0.787221  1.019096     3
ISF         0.265022  0.943611     3

==== K_26 4 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5233  0.098907  0.071399  8.134261e-06  0.046820  0.083452
FAR          5233  0.046530  0.100648  3.351751e-08  0.003386  0.012316
GreenRatio   5233  0.614139  0.242662  4.079327e-03  0.423898  0.668577
ISF          5233  0.190943  0.179927  2.408762e-04  0.057252  0.130458

                 75%       max  K_26
CoverRatio  0.132661  0.432481     4
FAR         0.042133  1.386081     4
GreenRatio  0.817763  1.006395     4
ISF         0.269548  0.930129     4

==== K_26 5 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   4213  0.105149  0.076442  9.296298e-06  0.045842  0.091380
FAR          4213  0.054923  0.114091  5.957378e-09  0.004011  0.018293
GreenRatio   4213  0.653722  0.259102  2.502904e-03  0.473054  0.717792
ISF          4213  0.174736  0.162325  1.693509e-04  0.053346  0.130163

                 75%       max  K_26
CoverRatio  0.150659  0.491169     5
FAR         0.057993  1.602930     5
GreenRatio  0.873662  1.023550     5
ISF         0.241419  0.936794     5

==== K_26 6 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5931  0.125373  0.076642  4.764353e-05  0.067860  0.113084
FAR          5931  0.068940  0.113964  1.933553e-07  0.007855  0.028257
GreenRatio   5931  0.433278  0.193114  5.382494e-04  0.290743  0.407816
ISF          5931  0.301440  0.178214  2.602956e-04  0.165218  0.274202

                 75%       max  K_26
CoverRatio  0.168663  0.472203     6
FAR         0.080540  1.682644     6
GreenRatio  0.557231  0.977678     6
ISF         0.413534  0.958027     6

==== K_26 7 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   4088  0.113081  0.072540  5.810187e-06  0.058044  0.103757
FAR          4088  0.057277  0.113068  1.689796e-08  0.005913  0.022600
GreenRatio   4088  0.721324  0.223970  2.155121e-03  0.596001  0.799855
ISF          4088  0.169111  0.158345  8.162428e-05  0.056147  0.120785

                 75%       max  K_26
CoverRatio  0.154628  0.545458     7
FAR         0.065040  1.717596     7
GreenRatio  0.892168  1.012245     7
ISF         0.226213  0.914776     7

==== K_26 8 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5063  0.089935  0.063410  5.810187e-06  0.041819  0.077614
FAR          5063  0.034099  0.080443  1.838343e-08  0.002778  0.010288
GreenRatio   5063  0.650570  0.227721  1.751060e-03  0.499911  0.710576
ISF          5063  0.165623  0.155894  8.199914e-05  0.049675  0.116599

                 75%       max  K_26
CoverRatio  0.124924  0.553607     8
FAR         0.034222  1.916308     8
GreenRatio  0.833697  1.014398     8
ISF         0.234338  0.882696     8

==== K_26 9 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   6330  0.200213  0.105609  1.394445e-05  0.119879  0.191325
FAR          6330  0.203186  0.241789  6.856020e-10  0.034676  0.118285
GreenRatio   6330  0.402925  0.182482  2.150296e-03  0.273878  0.383287
ISF          6330  0.471793  0.232132  5.020243e-04  0.292299  0.466098

                 75%       max  K_26
CoverRatio  0.272585  0.690947     9
FAR         0.277957  3.132435     9
GreenRatio  0.518559  0.998684     9
ISF         0.638239  0.997670     9

==== K_26 10 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   5381  0.136355  0.085465  9.877317e-05  0.075501  0.122264
FAR          5381  0.098229  0.179638  4.313095e-08  0.010796  0.035459
GreenRatio   5381  0.606946  0.237680  2.771690e-03  0.430412  0.648591
ISF          5381  0.274678  0.216111  5.034390e-04  0.105696  0.215406

                 75%       max  K_26
CoverRatio  0.178270  0.530655    10
FAR         0.095043  1.830768    10
GreenRatio  0.806437  0.992425    10
ISF         0.388449  0.990799    10

==== K_26 11 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   4424  0.113814  0.074303  4.648149e-06  0.060954  0.101913
FAR          4424  0.062736  0.145756  1.475787e-09  0.006503  0.022048
GreenRatio   4424  0.705881  0.222928  1.665732e-03  0.567564  0.763322
ISF          4424  0.192905  0.170797  8.292329e-05  0.066431  0.142493

                 75%       max  K_26
CoverRatio  0.152802  0.649123    11
FAR         0.059210  2.591573    11
GreenRatio  0.887241  1.021964    11
ISF         0.267335  0.963708    11

==== K_26 12 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   6863  0.120178  0.070142  1.162037e-06  0.069937  0.111328
FAR          6863  0.059209  0.111763  3.606189e-09  0.008240  0.025622
GreenRatio   6863  0.666804  0.219788  6.662928e-03  0.533250  0.721290
ISF          6863  0.215711  0.173793  2.487699e-04  0.087276  0.165909

                 75%       max  K_26
CoverRatio  0.159255  0.475485    12
FAR         0.064071  1.484431    12
GreenRatio  0.841038  1.008912    12
ISF         0.295868  0.962970    12

==== K_26 13 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   6217  0.163785  0.089511  4.299538e-05  0.097896  0.151340
FAR          6217  0.126952  0.180522  4.989014e-09  0.020187  0.058784
GreenRatio   6217  0.519128  0.226532  2.686993e-03  0.343401  0.515504
ISF          6217  0.354579  0.219527  5.310926e-04  0.166806  0.322434

                 75%       max  K_26
CoverRatio  0.217580  0.580585    13
FAR         0.156300  1.712297    13
GreenRatio  0.703280  0.997811    13
ISF         0.521588  0.986269    13

==== K_26 14 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   6511  0.235571  0.104729  8.250465e-05  0.157028  0.238284
FAR          6511  0.279054  0.257819  2.529111e-07  0.069906  0.205197
GreenRatio   6511  0.417245  0.177718  1.757826e-03  0.287930  0.412561
ISF          6511  0.550338  0.228267  9.149524e-03  0.377702  0.571507

                 75%       max  K_26
CoverRatio  0.316241  0.524949    14
FAR         0.424202  1.600126    14
GreenRatio  0.531767  0.976662    14
ISF         0.730886  0.992437    14

==== K_26 15 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   5590  0.180707  0.085926  0.000163  0.119114  0.170606  0.234269
FAR          5590  0.160873  0.215863  0.000002  0.037473  0.087715  0.184231
GreenRatio   5590  0.679455  0.212801  0.004731  0.554472  0.727824  0.845895
ISF          5590  0.326153  0.222200  0.005877  0.149090  0.266252  0.459023

                 max  K_26
CoverRatio  0.514522    15
FAR         2.465962    15
GreenRatio  1.010109    15
ISF         0.982757    15

==== K_26 16 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   4500  0.154326  0.074992  1.010972e-04  0.101311  0.150129
FAR          4500  0.092411  0.144867  1.172931e-07  0.022909  0.057991
GreenRatio   4500  0.725231  0.212876  3.871110e-03  0.606090  0.784734
ISF          4500  0.268987  0.180977  6.997669e-04  0.120073  0.238585

                 75%       max  K_26
CoverRatio  0.202840  0.671215    16
FAR         0.111742  3.566849    16
GreenRatio  0.890930  1.013975    16
ISF         0.383301  0.977504    16

==== K_26 17 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   7020  0.189332  0.090822  0.000413  0.124836  0.178839  0.246536
FAR          7020  0.176575  0.221081  0.000002  0.039376  0.094447  0.211911
GreenRatio   7020  0.591451  0.219144  0.001477  0.445834  0.622272  0.767552
ISF          7020  0.393153  0.227029  0.001836  0.206377  0.352892  0.559665

                 max  K_26
CoverRatio  0.534459    17
FAR         1.763074    17
GreenRatio  0.989594    17
ISF         0.994141    17

==== K_26 18 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   5444  0.150340  0.072114  0.000340  0.102663  0.143538  0.191227
FAR          5444  0.089695  0.149021  0.000001  0.022067  0.050037  0.099597
GreenRatio   5444  0.684067  0.206265  0.002420  0.566724  0.737169  0.844290
ISF          5444  0.258922  0.177531  0.000704  0.127796  0.216515  0.346454

                 max  K_26
CoverRatio  0.527836    18
FAR         2.093837    18
GreenRatio  1.001758    18
ISF         0.975394    18

==== K_26 19 (K=26) data ====
            count      mean       std           min       25%       50%  \
CoverRatio   3862  0.175068  0.092737  4.299538e-05  0.104285  0.171056
FAR          3862  0.132982  0.165296  1.566107e-07  0.027520  0.082415
GreenRatio   3862  0.651216  0.220815  8.081705e-04  0.515678  0.701369
ISF          3862  0.305104  0.206381  3.454724e-04  0.140789  0.267260

                 75%       max  K_26
CoverRatio  0.242138  0.578438    19
FAR         0.176710  1.742979    19
GreenRatio  0.825535  1.015496    19
ISF         0.434288  0.975727    19

==== K_26 20 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   4527  0.285566  0.105556  0.003474  0.206742  0.296716  0.376602
FAR          4527  0.413348  0.317935  0.000068  0.136022  0.354624  0.637786
GreenRatio   4527  0.411911  0.173979  0.005757  0.286913  0.404143  0.529108
ISF          4527  0.662606  0.228281  0.016108  0.495241  0.706228  0.857312

                 max  K_26
CoverRatio  0.513738    20
FAR         1.727876    20
GreenRatio  0.950644    20
ISF         0.994384    20

==== K_26 21 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   5878  0.191745  0.074834  0.000387  0.141050  0.188176  0.243155
FAR          5878  0.138985  0.160479  0.000002  0.054977  0.104487  0.167179
GreenRatio   5878  0.714652  0.194408  0.011651  0.607495  0.766375  0.862833
ISF          5878  0.341839  0.196291  0.002100  0.183613  0.317035  0.474940

                 max  K_26
CoverRatio  0.590271    21
FAR         2.231233    21
GreenRatio  0.992886    21
ISF         0.992112    21

==== K_26 22 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   6751  0.203310  0.084511  0.000446  0.147519  0.195344  0.251800
FAR          6751  0.196086  0.257190  0.000003  0.054708  0.106030  0.199480
GreenRatio   6751  0.637693  0.197470  0.000343  0.515923  0.675563  0.790843
ISF          6751  0.386678  0.216864  0.005985  0.214430  0.334348  0.534771

                 max  K_26
CoverRatio  0.703138    22
FAR         2.483490    22
GreenRatio  1.004794    22
ISF         0.996819    22

==== K_26 23 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   6364  0.239239  0.089973  0.001470  0.175881  0.239588  0.305897
FAR          6364  0.266117  0.246821  0.000024  0.097970  0.189535  0.350433
GreenRatio   6364  0.585372  0.190962  0.000559  0.467715  0.616292  0.725462
ISF          6364  0.509885  0.215323  0.016489  0.343304  0.501114  0.673765

                 max  K_26
CoverRatio  0.527604    23
FAR         2.162388    23
GreenRatio  0.988329    23
ISF         0.994234    23

==== K_26 24 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   6356  0.219792  0.074906  0.002546  0.167527  0.218442  0.268522
FAR          6356  0.195534  0.194660  0.000044  0.084642  0.146130  0.225893
GreenRatio   6356  0.688318  0.186944  0.000384  0.581542  0.727799  0.830964
ISF          6356  0.408501  0.201979  0.006775  0.246863  0.386258  0.549679

                 max  K_26
CoverRatio  0.621567    24
FAR         2.027358    24
GreenRatio  0.997231    24
ISF         0.977522    24

==== K_26 25 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
CoverRatio   6228  0.236820  0.075397  0.000478  0.189576  0.233828  0.281455
FAR          6228  0.231314  0.221214  0.000002  0.104325  0.167248  0.274603
GreenRatio   6228  0.626984  0.192287  0.000636  0.510945  0.658533  0.772549
ISF          6228  0.483717  0.198072  0.055831  0.329708  0.463803  0.624691

                 max  K_26
CoverRatio  0.611264    25
FAR         2.302672    25
GreenRatio  0.996508    25
ISF         0.994756    25

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\216867145.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.


In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 创建一个空的 DataFrame 用于存储所有 cluster 的统计数据
    all_cluster_stats = []

    # 遍历每个 cluster 进行绘制
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'K_{K}'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
        # 输出 describe() 的 count 为整数
        describe_output = cluster_data[columns_to_plot].describe().transpose()
        describe_output['count'] = describe_output['count'].astype(int)

        # 记录 cluster 统计信息
        describe_output[f'K_{K}'] = cluster_id
        all_cluster_stats.append(describe_output)

        # 打印统计信息
        print(f"\n==== Cluster {cluster_id} (K={K}) data ====")
        print(describe_output)

        # 创建图像
        plt.figure(figsize=(10, 6))

        for column in columns_to_plot:
            # 绘制直方图
            sns.histplot(cluster_data[column], bins=20, kde=False, label=f'{column} Histogram', stat="proportion", alpha=0.3)

            # 计算直方图数据
            counts, bin_edges = np.histogram(cluster_data[column], bins=10, density=False)
            total_count = counts.sum()  # 总样本数
            proportions = counts / total_count  # 计算 proportion

            # 计算 bin 的中心位置
            bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

            # 绘制 proportion 曲线
            plt.plot(bin_centers, proportions, marker='o', linestyle='-', label=f'{column} Proportion Curve')

        plt.title(f'K_{K} {cluster_id} Histogram with Proportion Curve')
        plt.xlabel('Value')
        plt.ylabel('Proportion')
        plt.xlim(0, 15)
        plt.ylim(0, 1)
        plt.legend()

        # 保存直方图图像
        output_hist_path = os.path.join(output_folder, rf'K_{K}_histogram_cluster_{cluster_id}.png')
        plt.savefig(output_hist_path)
        plt.close()  # 关闭图像，避免影响下一个 cluster


    # 合并所有统计数据到一个 DataFrame
    stats_df = pd.concat(all_cluster_stats)
    stats_df.to_csv(os.path.join(output_folder, 'cluster_stats.csv'))

def plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 创建绘图
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'K_{K}'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]

        # 将数据从宽格式转换为长格式
        cluster_data_melted = cluster_data.melt(id_vars=[f'K_{K}'], value_vars=columns_to_plot, var_name='Variable', value_name='Value')

        # 创建一个新的图像
        plt.figure(figsize=(4, 6))

        # 绘制小提琴图
        sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')

        # 绘制箱线图
        sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

        # 设置图像标题和标签
        plt.title(f'K_{K} {cluster_id} Data Distribution')
        plt.xlabel('Variable')
        plt.ylabel('Value')
        plt.ylim(-1.5, 15)
        plt.tight_layout()

        # 保存图像
        output_image_path = os.path.join(output_folder, rf'K_{K}_boxplot_cluster_{cluster_id}.png')

        plt.savefig(output_image_path)
        plt.close()

# 运行代码
input_csv_path = r"D:\file\e_index\223_cities_cluster_with_index.csv"
columns_to_plot = ['Buiheight', 'GrVolRatio']

for K in [5,12,20,26]:
    output_folder = rf'D:\file\e_index\fig\bui_new2\{K}'
    os.makedirs(output_folder, exist_ok=True)

    plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder)
    plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder)

==== Cluster 0 (K=5) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   26187  1.268156  1.343302  0.000195  0.298726  0.793215  1.758758
GrVolRatio  26187  1.692654  2.482586  0.000024  0.197377  0.480943  2.024267

                  max  K_5
Buiheight   13.600608    0
GrVolRatio  16.780441    0

==== Cluster 1 (K=5) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   27383  1.157500  1.203067  0.000288  0.355223  0.857372  1.564111
GrVolRatio  27383  3.590496  2.981512  0.000032  1.148827  2.840804  5.430906

                  max  K_5
Buiheight   15.942061    1
GrVolRatio  18.572041    1

==== Cluster 2 (K=5) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   36963  1.265382  1.345997  0.000245  0.408318  0.903411  1.608838
GrVolRatio  36963  3.268512  2.535508  0.000062  0.968769  2.938902  5.052294

                  max  K_5
Buiheight   16.496742    2
GrVolRatio  16.495376    2

==== Cluster 3 (K=5) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   27743  2.401283  1.819616  0.000148  1.031738  1.931996  3.358784
GrVolRatio  27743  1.394064  1.613980  0.000034  0.282950  0.710598  1.980184

                  max  K_5
Buiheight   15.387312    3
GrVolRatio  15.347659    3

==== Cluster 4 (K=5) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   23916  2.553420  1.793741  0.012730  1.424364  2.029510  3.058858
GrVolRatio  23916  1.818301  1.568217  0.000006  0.586194  1.406537  2.633585

                  max  K_5
Buiheight   14.545104    4
GrVolRatio  11.568650    4

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

==== Cluster 0 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   12428  1.022389  1.201687  0.000195  0.220227  0.555402  1.354801
GrVolRatio  12428  2.601426  3.026470  0.000053  0.231451  0.937068  4.642457

                  max  K_12
Buiheight   11.173186     0
GrVolRatio  16.780441     0

==== Cluster 1 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   14784  0.894155  1.130356  0.000288  0.229496  0.557901  1.128627
GrVolRatio  14784  4.092083  3.274615  0.000105  1.138744  3.615973  6.294909

                  max  K_12
Buiheight   13.274631     1
GrVolRatio  18.249425     1

==== Cluster 2 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    8358  2.175529  1.719645  0.000148  0.822814  1.783888  3.076278
GrVolRatio   8358  0.574126  0.816022  0.000024  0.160115  0.322827  0.609261

                  max  K_12
Buiheight   13.600608     2
GrVolRatio  10.015994     2

==== Cluster 3 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    8213  1.126821  1.092828  0.001067  0.363159  0.798560  1.520427
GrVolRatio   8213  1.091449  1.537973  0.000044  0.211527  0.443835  1.213071

                 max  K_12
Buiheight   12.79592     3
GrVolRatio  13.71441     3

==== Cluster 4 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   18450  0.884895  1.091636  0.000530  0.239066  0.538143  1.077100
GrVolRatio  18450  3.408752  2.738630  0.000163  0.791540  3.087680  5.412302

                  max  K_12
Buiheight   13.968932     4
GrVolRatio  16.495376     4

==== Cluster 5 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   13278  1.963624  1.642403  0.000230  0.828194  1.484848  2.574733
GrVolRatio  13278  1.737653  1.840676  0.000034  0.325874  0.951772  2.772999

                  max  K_12
Buiheight   14.482531     5
GrVolRatio  15.347659     5

==== Cluster 6 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   17981  1.586970  1.465949  0.000245  0.718477  1.223022  1.887444
GrVolRatio  17981  3.199325  2.354098  0.000062  1.117622  2.936858  4.814911

                  max  K_12
Buiheight   16.496742     6
GrVolRatio  15.425709     6

==== Cluster 7 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    8047  3.444084  1.957836  0.007430  1.871339  3.370305  4.807697
GrVolRatio   8047  0.515761  0.656568  0.000177  0.158981  0.318149  0.604323

                  max  K_12
Buiheight   13.119917     7
GrVolRatio   9.157799     7

==== Cluster 8 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   13660  1.505343  1.227323  0.000338  0.726096  1.308114  1.920133
GrVolRatio  13660  2.951336  2.436406  0.000032  1.128990  2.283467  4.130331

                  max  K_12
Buiheight   15.942061     8
GrVolRatio  18.572041     8

==== Cluster 9 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    8342  2.283819  1.912509  0.012730  1.132075  1.681408  2.618371
GrVolRatio   8342  1.951914  1.726063  0.000014  0.536573  1.508399  2.943782

                  max  K_12
Buiheight   14.288724     9
GrVolRatio  11.568650     9

==== Cluster 10 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    8943  2.776203  1.707108  0.013957  1.697436  2.357819  3.410913
GrVolRatio   8943  1.485016  1.239143  0.000006  0.626178  1.131209  2.008151

                  max  K_12
Buiheight   15.387312    10
GrVolRatio  12.430377    10

==== Cluster 11 (K=12) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    9708  2.359835  1.509901  0.033328  1.516351  2.007849  2.654173
GrVolRatio   9708  2.215657  1.537328  0.000084  1.062148  1.897096  3.014598

                 max  K_12
Buiheight   14.52066    11
GrVolRatio  10.89650    11

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

==== Cluster 0 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5695  1.836842  1.538883  0.001009  0.618348  1.386818  2.710889
GrVolRatio   5695  0.532307  0.920476  0.000053  0.118815  0.266381  0.562283

                  max  K_20
Buiheight    9.128597     0
GrVolRatio  11.786160     0

==== Cluster 1 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    7328  1.044019  1.222102  0.000195  0.269100  0.650547  1.324771
GrVolRatio   7328  3.758961  2.921233  0.000250  0.921859  3.572091  5.822357

                  max  K_20
Buiheight   13.968932     1
GrVolRatio  16.135795     1

==== Cluster 2 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5910  0.817788  0.931006  0.000725  0.234738  0.487901  1.049290
GrVolRatio   5910  0.871259  1.349804  0.001354  0.181706  0.361685  0.896028

                  max  K_20
Buiheight   11.173186     2
GrVolRatio  12.673931     2

==== Cluster 3 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6761  0.849423  1.114932  0.000288  0.190745  0.491367  1.058002
GrVolRatio   6761  3.909253  3.469164  0.000116  0.859465  3.107191  6.150419

                  max  K_20
Buiheight   12.909019     3
GrVolRatio  18.249425     3

==== Cluster 4 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    9645  0.655035  0.867014  0.000303  0.171262  0.337764  0.794056
GrVolRatio   9645  3.716340  2.990655  0.000276  0.775006  3.466674  5.941491

                  max  K_20
Buiheight   10.762145     4
GrVolRatio  16.780441     4

==== Cluster 5 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6207  0.914260  1.108725  0.000952  0.255090  0.604437  1.174099
GrVolRatio   6207  4.265391  3.084103  0.000105  1.467025  4.048509  6.404310

                  max  K_20
Buiheight   13.274631     5
GrVolRatio  17.037898     5

==== Cluster 6 (K=20) data ====
            count     mean       std       min       25%       50%       75%  \
Buiheight    5834  2.26571  1.742666  0.000148  0.914015  1.899943  3.188191
GrVolRatio   5834  0.65109  0.959785  0.000024  0.167302  0.336416  0.654961

                  max  K_20
Buiheight   13.600608     6
GrVolRatio  10.015994     6

==== Cluster 7 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    7238  1.321583  1.235202  0.000457  0.469041  0.958410  1.757341
GrVolRatio   7238  1.454864  1.808744  0.000044  0.250590  0.634183  2.028492

                  max  K_20
Buiheight   14.482531     7
GrVolRatio  13.714410     7

==== Cluster 8 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight   10663  0.948335  1.019081  0.000245  0.331285  0.684627  1.187950
GrVolRatio  10663  3.516183  2.638352  0.000163  1.160483  3.273271  5.365973

                  max  K_20
Buiheight   11.608483     8
GrVolRatio  16.495376     8

==== Cluster 9 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    7274  1.188523  1.242519  0.000733  0.466960  0.909278  1.478030
GrVolRatio   7274  3.753815  2.868174  0.000041  1.368265  3.154502  5.655428

                  max  K_20
Buiheight   15.942061     9
GrVolRatio  18.572041     9

==== Cluster 10 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    7887  1.746726  1.631253  0.010886  0.723859  1.300578  2.117787
GrVolRatio   7887  3.080105  2.381443  0.000358  0.912521  2.764199  4.767727

                  max  K_20
Buiheight   16.496742    10
GrVolRatio  14.285828    10

==== Cluster 11 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6990  2.413525  1.750300  0.006109  1.037490  2.021457  3.431589
GrVolRatio   6990  0.785627  1.077594  0.000034  0.185394  0.404007  0.856485

                  max  K_20
Buiheight   11.191711    11
GrVolRatio  11.148237    11

==== Cluster 12 (K=20) data ====
            count      mean      std       min       25%       50%       75%  \
Buiheight    7563  2.026538  1.68888  0.000230  0.890388  1.535255  2.561630
GrVolRatio   7563  2.110374  1.91989  0.000175  0.507292  1.505747  3.335141

                  max  K_20
Buiheight   12.639485    12
GrVolRatio  15.347659    12

==== Cluster 13 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5517  1.636299  1.342673  0.000338  0.752778  1.380454  2.106743
GrVolRatio   5517  2.603620  2.205995  0.000032  1.026546  2.036510  3.557489

                  max  K_20
Buiheight   14.182015    13
GrVolRatio  16.460552    13

==== Cluster 14 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5596  3.721146  1.963590  0.007430  2.159372  3.682390  5.055319
GrVolRatio   5596  0.484602  0.638837  0.000211  0.147525  0.291779  0.558654

                  max  K_20
Buiheight   13.119917    14
GrVolRatio   9.157799    14

==== Cluster 15 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    9639  1.666395  1.257154  0.008329  0.950440  1.457026  1.980176
GrVolRatio   9639  2.961892  2.157925  0.000062  1.171671  2.558624  4.350209

                  max  K_20
Buiheight   13.863989    15
GrVolRatio  13.920503    15

==== Cluster 16 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6998  2.255066  1.937797  0.012730  1.116095  1.646659  2.488689
GrVolRatio   6998  2.059379  1.716109  0.000014  0.646181  1.684261  3.060288

                  max  K_20
Buiheight   14.288724    16
GrVolRatio  11.568650    16

==== Cluster 17 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    7018  2.797764  1.769722  0.028165  1.636768  2.361643  3.545670
GrVolRatio   7018  1.499458  1.292653  0.000067  0.594636  1.100018  2.057257

                  max  K_20
Buiheight   15.387312    17
GrVolRatio  12.430377    17

==== Cluster 18 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5707  2.276726  1.418993  0.043817  1.491136  1.986495  2.553543
GrVolRatio   5707  2.400353  1.742731  0.000084  1.033979  2.028783  3.436201

                  max  K_20
Buiheight   12.304468    18
GrVolRatio  10.896500    18

==== Cluster 19 (K=20) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6722  2.506170  1.599358  0.013957  1.572488  2.097599  2.874972
GrVolRatio   6722  1.787059  1.222479  0.000006  0.876912  1.556581  2.419275

                  max  K_20
Buiheight   14.545104    19
GrVolRatio   9.602569    19

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:


==== Cluster 0 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    3368  1.201500  1.152594  0.000195  0.287378  0.881221  1.697805
GrVolRatio   3368  4.198906  3.296692  0.000053  0.727542  4.136709  6.559951

                  max  K_26
Buiheight    7.507823     0
GrVolRatio  16.135795     0

==== Cluster 1 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5684  1.577379  1.517022  0.001009  0.415227  1.004852  2.318873
GrVolRatio   5684  0.506998  0.741328  0.000107  0.138647  0.288062  0.566421

                  max  K_26
Buiheight    9.128597     1
GrVolRatio  10.316740     1

==== Cluster 2 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    4295  0.793388  1.106802  0.000288  0.164831  0.407108  0.961082
GrVolRatio   4295  3.908521  3.501683  0.000239  0.788342  2.992739  6.330254

                  max  K_26
Buiheight   12.909019     2
GrVolRatio  18.249425     2

==== Cluster 3 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6009  0.683471  0.933854  0.000303  0.167791  0.337907  0.812344
GrVolRatio   6009  2.812123  2.991015  0.001240  0.324755  1.438037  4.946539

                  max  K_26
Buiheight   11.173186     3
GrVolRatio  16.780441     3

==== Cluster 4 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5236  0.797918  0.985009  0.002413  0.210311  0.448793  0.983946
GrVolRatio   5236  3.385347  2.787045  0.000250  0.666853  3.033226  5.464340

                  max  K_26
Buiheight   10.490413     4
GrVolRatio  16.492488     4

==== Cluster 5 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    4244  0.928153  1.116649  0.000338  0.244665  0.603123  1.183836
GrVolRatio   4244  3.773565  3.241160  0.000083  1.026136  3.104251  5.699538

                  max  K_26
Buiheight   10.205738     5
GrVolRatio  17.771209     5

==== Cluster 6 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5933  1.079314  1.057110  0.001067  0.340930  0.756782  1.459014
GrVolRatio   5933  0.940992  1.376427  0.000044  0.204131  0.401786  1.001021

                 max  K_26
Buiheight   12.79592     6
GrVolRatio  13.71441     6

==== Cluster 7 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    4091  0.962946  1.073393  0.001229  0.300986  0.675052  1.261132
GrVolRatio   4091  4.231389  2.971880  0.000105  1.587956  4.077476  6.294332

                  max  K_26
Buiheight   13.274631     7
GrVolRatio  17.037898     7

==== Cluster 8 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5072  0.664920  0.812684  0.000813  0.194872  0.400042  0.850734
GrVolRatio   5072  3.723525  2.839337  0.000473  1.109411  3.485079  5.784440

                  max  K_26
Buiheight   10.384478     8
GrVolRatio  15.954302     8

==== Cluster 9 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6332  2.212604  1.720724  0.000148  0.886063  1.835539  3.083834
GrVolRatio   6332  0.662681  0.987310  0.000024  0.167518  0.337059  0.664119

                  max  K_26
Buiheight   13.600608     9
GrVolRatio  10.015994     9

==== Cluster 10 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5382  1.347224  1.496726  0.001310  0.431384  0.878666  1.634836
GrVolRatio   5382  2.884236  2.499696  0.000163  0.549966  2.378842  4.757911

                  max  K_26
Buiheight   13.968932    10
GrVolRatio  14.426014    10

==== Cluster 11 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    4428  0.997797  1.241368  0.000733  0.317966  0.661364  1.178856
GrVolRatio   4428  4.218158  3.172966  0.000041  1.366960  3.845642  6.404077

                  max  K_26
Buiheight   13.190389    11
GrVolRatio  18.572041    11

==== Cluster 12 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6864  0.977870  1.026097  0.000245  0.352759  0.704805  1.221184
GrVolRatio   6864  3.536549  2.612895  0.001416  1.157805  3.358591  5.381254

                  max  K_26
Buiheight   11.289275    12
GrVolRatio  16.495376    12

==== Cluster 13 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6219  1.624137  1.458275  0.000230  0.622108  1.170678  2.149944
GrVolRatio   6219  1.592770  1.868049  0.000088  0.270948  0.744123  2.375742

                  max  K_26
Buiheight   14.482531    13
GrVolRatio  15.347659    13

==== Cluster 14 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6512  2.819981  1.821464  0.009196  1.323818  2.589346  4.032804
GrVolRatio   6512  0.650801  0.863318  0.000034  0.174861  0.366094  0.724244

                  max  K_26
Buiheight   11.712910    14
GrVolRatio   9.197803    14

==== Cluster 15 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5590  1.999763  1.704033  0.012329  0.936541  1.539357  2.367798
GrVolRatio   5590  3.004691  2.349554  0.000439  0.922542  2.583071  4.641262

                  max  K_26
Buiheight   16.496742    15
GrVolRatio  13.723346    15

==== Cluster 16 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    4501  1.352583  1.187743  0.000807  0.677963  1.153249  1.665670
GrVolRatio   4501  3.392240  2.606359  0.000280  1.352255  2.783401  4.870205

                  max  K_26
Buiheight   15.942061    16
GrVolRatio  16.460552    16

==== Cluster 17 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    7020  2.085353  1.711677  0.012562  0.926830  1.583329  2.629216
GrVolRatio   7020  2.077892  1.887427  0.000175  0.506954  1.473158  3.275862

                  max  K_26
Buiheight   12.639485    17
GrVolRatio  12.264812    17

==== Cluster 18 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5444  1.319841  1.213970  0.010886  0.650270  1.063395  1.579146
GrVolRatio   5444  3.216393  2.309454  0.000062  1.291343  2.931524  4.697835

                  max  K_26
Buiheight   11.937679    18
GrVolRatio  15.425709    18

==== Cluster 19 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    3863  1.696226  1.363654  0.003658  0.777567  1.451688  2.190538
GrVolRatio   3863  2.468642  2.063867  0.000032  1.002878  1.957342  3.325539

                  max  K_26
Buiheight   14.182015    19
GrVolRatio  15.311685    19

==== Cluster 20 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    4527  3.668645  2.045412  0.048936  1.975871  3.557806  5.108247
GrVolRatio   4527  0.517523  0.695118  0.000211  0.145342  0.290264  0.595964

                  max  K_26
Buiheight   13.119917    20
GrVolRatio   9.157799    20

==== Cluster 21 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    5878  1.810406  1.224662  0.008329  1.140131  1.627915  2.102962
GrVolRatio   5878  2.826089  2.081615  0.000886  1.151817  2.363182  4.094741

                  max  K_26
Buiheight   13.863989    21
GrVolRatio  13.205470    21

==== Cluster 22 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6751  2.226704  1.932082  0.012730  1.111929  1.632305  2.417816
GrVolRatio   6751  2.123299  1.713781  0.000014  0.711498  1.782009  3.116734

                  max  K_26
Buiheight   14.288724    22
GrVolRatio  11.568650    22

==== Cluster 23 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6365  2.798755  1.784757  0.007430  1.639345  2.354489  3.505714
GrVolRatio   6365  1.530407  1.308110  0.000067  0.613379  1.128642  2.095585

                  max  K_26
Buiheight   15.387312    23
GrVolRatio  12.430377    23

==== Cluster 24 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6356  2.296152  1.443084  0.043817  1.495244  1.992855  2.579492
GrVolRatio   6356  2.392544  1.712448  0.000084  1.056213  2.049967  3.389404

                 max  K_26
Buiheight   14.52066    24
GrVolRatio  10.89650    24

==== Cluster 25 (K=26) data ====
            count      mean       std       min       25%       50%       75%  \
Buiheight    6228  2.539294  1.586113  0.013957  1.599298  2.136242  2.931858
GrVolRatio   6228  1.708583  1.180086  0.000006  0.842071  1.470185  2.318078

                  max  K_26
Buiheight   14.545104    25
GrVolRatio   9.602569    25

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:93: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\3171993045.py:90: FutureWarning:


# 11_02 ['MIN_DistWB', 'MIN_DistGL', 'MIN_DistMT']

In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

def plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 用来存储统计信息
    stats_df = pd.DataFrame()

    # 遍历每个 cluster 进行绘制
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'K_{K}'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
        # 过滤距离大于 1000 的数据
        cluster_data = cluster_data[(cluster_data[columns_to_plot] <= 1000).all(axis=1)]

        # 计算统计信息
        describe_output = cluster_data[columns_to_plot].describe().transpose()
        describe_output[f'K_{K}'] = cluster_id
        stats_df = pd.concat([stats_df, describe_output])

        # 创建绘图
        plt.figure(figsize=(10, 6))

        for column in columns_to_plot:
            # 计算直方图数据
            counts, bin_edges = np.histogram(cluster_data[column], bins=10, density=False)
            total_count = counts.sum()
            proportions = counts / total_count  # 计算 proportion
            bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2  # 计算 bin 的中心位置

            # 绘制直方图 (proportion)
            sns.histplot(cluster_data[column], bins=10, stat="proportion", alpha=0.3, label=f'{column} Histogram')

            # 绘制 proportion 曲线
            plt.plot(bin_centers, proportions, marker='o', linestyle='-', label=f'{column} Proportion Curve')

        # 设置标题和坐标轴
        plt.title(f'K_{K} {cluster_id} Histogram with Proportion Curve (K={K})')
        plt.xlabel('Value')
        plt.ylabel('Proportion')
        plt.ylim(0, 1)
        plt.legend()

        # 保存图像
        output_hist_path = os.path.join(output_folder, rf'K={K}_histogram_cluster_{cluster_id}.png')
        plt.savefig(output_hist_path)
        plt.close()

    # 将统计信息导出为 CSV 文件
    stats_output_path = os.path.join(output_folder, rf'K={K}_cluster_stats.csv')
    stats_df.to_csv(stats_output_path)
    print(f"统计结果已保存: {stats_output_path}")

def plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 创建绘图
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'K_{K}'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
        # 假设你的列值表示距离，可以进行如下条件过滤
        cluster_data = cluster_data[(cluster_data[columns_to_plot] <= 1000).all(axis=1)]

        # 将数据从宽格式转换为长格式
        cluster_data_melted = cluster_data.melt(id_vars=[f'K_{K}'], value_vars=columns_to_plot, var_name='Variable', value_name='Value')

        # 创建一个新的图像
        plt.figure(figsize=(12, 6))

        # 绘制小提琴图
        sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')

        # 绘制箱线图
        sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

        # 设置图像标题和标签
        plt.title(f'K_{K} {cluster_id} Data Distribution')
        plt.xlabel('Variable')
        plt.ylabel('Value')
        # 调整布局
        plt.tight_layout()
        plt.ylim(-200, 1200)

        # 保存图像
        output_image_path = os.path.join(output_folder, rf'K={K}_boxplot_cluster_{cluster_id}.png')

        plt.savefig(output_image_path)
        plt.close()


# 运行代码
input_csv_path = r"D:\file\e_index\223_cities_cluster_with_index.csv"
columns_to_plot = ['MIN_DistWB', 'MIN_DistGL', 'MIN_DistMT','elev_mean', 'elev_std', 'elev_range']
columns_to_plot_2 = ['MIN_DistWB', 'MIN_DistGL', 'MIN_DistMT']

for K in [5,12,20,26]:
    output_folder = rf'D:\file\e_index\fig\dist\{K}'
    os.makedirs(output_folder, exist_ok=True)

    plot_cluster_histograms(input_csv_path, columns_to_plot_2, K, output_folder)
    plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder)

统计结果已保存: D:\file\e_index\fig\dist\5\K=5_cluster_stats.csv

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

统计结果已保存: D:\file\e_index\fig\dist\12\K=12_cluster_stats.csv

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

统计结果已保存: D:\file\e_index\fig\dist\20\K=20_cluster_stats.csv

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.


统计结果已保存: D:\file\e_index\fig\dist\26\K=26_cluster_stats.csv

C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:83: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_26344\29903029.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.


In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

def plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 用来存储统计信息
    stats_df = pd.DataFrame()

    # 遍历每个 cluster 进行绘制
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df['Cluster'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]

        # 计算统计信息
        describe_output = cluster_data[columns_to_plot].describe().transpose()
        describe_output['Cluster'] = cluster_id
        stats_df = pd.concat([stats_df, describe_output])

        # 创建绘图
        plt.figure(figsize=(10, 6))

        for column in columns_to_plot:
            # 计算直方图数据
            counts, bin_edges = np.histogram(cluster_data[column], bins=10, density=False)
            total_count = counts.sum()
            proportions = counts / total_count  # 计算 proportion
            bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2  # 计算 bin 的中心位置

            # 绘制直方图 (proportion)
            sns.histplot(cluster_data[column], bins=20, stat="proportion", alpha=0.3, label=f'{column} Histogram')

            # 绘制 proportion 曲线
            plt.plot(bin_centers, proportions, marker='o', linestyle='-', label=f'{column} Proportion Curve')

        # 设置标题和坐标轴
        plt.title(f'Cluster {cluster_id} Histogram with Proportion Curve (K={K})')
        plt.xlabel('Value')
        plt.ylabel('Proportion')
        plt.ylim(0, 1)
        plt.xlim(-0.3, 1000)
        plt.legend()

        # 保存图像
        output_hist_path = os.path.join(output_folder, rf'K={K}_histogram_cluster_{cluster_id}.png')
        plt.savefig(output_hist_path)
        plt.close()

    # 将统计信息导出为 CSV 文件
    stats_output_path = os.path.join(output_folder, rf'K={K}_cluster_stats.csv')
    stats_df.to_csv(stats_output_path)
    print(f"统计结果已保存: {stats_output_path}")

def plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 创建绘图
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'Cluster'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]

        # 将数据从宽格式转换为长格式
        cluster_data_melted = cluster_data.melt(id_vars=[f'Cluster'], value_vars=columns_to_plot, var_name='Variable', value_name='Value')

        # 创建一个新的图像
        plt.figure(figsize=(6, 6))

        # 绘制小提琴图
        sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')

        # 绘制箱线图
        sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

        # 设置图像标题和标签
        plt.title(f'Cluster {cluster_id} Data Distribution')
        plt.xlabel('Variable')
        plt.ylabel('Value')
        # 调整布局
        plt.tight_layout()
        plt.ylim(-80, 1000)

        # 保存图像
        output_image_path = os.path.join(output_folder, rf'K={K}_boxplot_cluster_{cluster_id}.png')

        plt.savefig(output_image_path)
        plt.close()


# 运行代码
input_csv_path = r"D:\file\e_index/223_cities_cluster_with_index.csv"
columns_to_plot = ['elev_mean', 'elev_std', 'elev_range']

for K in range(11, 12):
    output_folder = rf'D:\file\e_index\fig\elevation'
    os.makedirs(output_folder, exist_ok=True)

    plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder)
    plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder)

统计结果已保存: D:\file\e_index\fig\elevation\K=11_cluster_stats.csv

C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:77: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3177384436.py:80: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

def plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 用来存储统计信息
    stats_df = pd.DataFrame()

    # 遍历每个 cluster 进行绘制
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df['Cluster'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
        # 过滤距离大于 1000 的数据
        cluster_data = cluster_data[(cluster_data[columns_to_plot] <= 1000).all(axis=1)]

        # 计算统计信息
        describe_output = cluster_data[columns_to_plot].describe().transpose()
        describe_output['Cluster'] = cluster_id
        stats_df = pd.concat([stats_df, describe_output])

        # 创建绘图
        plt.figure(figsize=(10, 6))

        for column in columns_to_plot:
            # 计算直方图数据
            counts, bin_edges = np.histogram(cluster_data[column], bins=10, density=False)
            total_count = counts.sum()
            proportions = counts / total_count  # 计算 proportion
            bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2  # 计算 bin 的中心位置

            # 绘制直方图 (proportion)
            sns.histplot(cluster_data[column], bins=10, stat="proportion", alpha=0.3, label=f'{column} Histogram')

            # 绘制 proportion 曲线
            plt.plot(bin_centers, proportions, marker='o', linestyle='-', label=f'{column} Proportion Curve')

        # 设置标题和坐标轴
        plt.title(f'Cluster {cluster_id} Histogram with Proportion Curve (K={K})')
        plt.xlabel('Value')
        plt.ylabel('Proportion')
        plt.ylim(0, 1)
        plt.legend(loc='upper center')  # 固定图例位置


        # 保存图像
        output_hist_path = os.path.join(output_folder, rf'K={K}_histogram_cluster_{cluster_id}.png')
        plt.savefig(output_hist_path)
        plt.close()

    # 将统计信息导出为 CSV 文件
    stats_output_path = os.path.join(output_folder, rf'K={K}_cluster_stats.csv')
    stats_df.to_csv(stats_output_path)
    print(f"统计结果已保存: {stats_output_path}")

def plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder):
    # 读取数据
    df = pd.read_csv(input_csv_path)

    # 创建绘图
    for cluster_id in range(K):
        # 选择属于当前 cluster_id 的数据
        cluster_data = df[df[f'Cluster'] == cluster_id]
        # 过滤掉值为 -9999 的数据
        cluster_data = cluster_data[~cluster_data[columns_to_plot].isin([-9999]).any(axis=1)]
        # 假设你的列值表示距离，可以进行如下条件过滤
        cluster_data = cluster_data[(cluster_data[columns_to_plot] <= 1000).all(axis=1)]

        # 将数据从宽格式转换为长格式
        cluster_data_melted = cluster_data.melt(id_vars=[f'Cluster'], value_vars=columns_to_plot, var_name='Variable', value_name='Value')

        # 创建一个新的图像
        plt.figure(figsize=(6, 6))

        # 绘制小提琴图
        sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')

        # 绘制箱线图
        sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)

        # 设置图像标题和标签
        plt.title(f'Cluster {cluster_id} Data Distribution')
        plt.xlabel('Variable')
        plt.ylabel('Value')
        # 调整布局
        plt.tight_layout()
        plt.ylim(-20, 120)

        # 保存图像
        output_image_path = os.path.join(output_folder, rf'K={K}_boxplot_cluster_{cluster_id}.png')

        plt.savefig(output_image_path)
        plt.close()


# 运行代码
input_csv_path = r"D:\file\e_index/223_cities_cluster_with_index.csv"
columns_to_plot = ['slope_mean', 'slope_std', 'slope_rang']

for K in range(11, 12):
    output_folder = rf'D:\file\e_index\fig\slope'
    os.makedirs(output_folder, exist_ok=True)

    plot_cluster_histograms(input_csv_path, columns_to_plot, K, output_folder)
    plot_cluster_analysis(input_csv_path, columns_to_plot, K, output_folder)

统计结果已保存: D:\file\e_index\fig\slope\K=11_cluster_stats.csv

C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:81: FutureWarning:

The `scale` parameter has been renamed and will be removed in v0.15.0. Pass `density_norm='width'` for the same effect.
  sns.violinplot(x='Variable', y='Value', data=cluster_data_melted, inner=None, scale='width', palette='Set3')
C:\Users\owner\AppData\Local\Temp\ipykernel_51872\3735210612.py:84: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Variable', y='Value', data=cluster_data_melted, whis=1.5, width=0.2, palette='Set2', fliersize=0)